### ISSUE TITLE
Broken religion provinces

### ISSUE THREAD

**Issue by Rigmored** [Middle-Earth-Project-Team/mod#127]
There are provinces with noreligion in Harad, Rhun, Lossoth, Caradhras, Tir Sirannon and more, don't know how to fix it, files seem okay

**Comment by Lonhaldar** [comment]
Noticed it too, and like you said, the files looks good.

**Comment by Lonhaldar** [comment]
Ok, the problem seems to come from a wrong name in the province files : 
The game don't recognize any accent, and some province files were renamed with these accents. I'm fixing it currently

**Comment by Rigmored** [comment]
I had to add the accents for the game to recognise them at all, before that they were wasteland. 
Seems odd, that they could recognise the culture, title name, baronies etc but not religion only, because of the accent

**Comment by Lonhaldar** [comment]
Well, it doesn't seems to fix the thing. But i've got errors (not in validator, but in the logs) with the accent in the files names, it was impossible for the game to read them

**Comment by Rigmored** [comment]
Odd

**Comment by Rigmored** [comment]
Seems removing them has now made those provinces a wasteland once again

**Comment by RiccoPT** [comment]
Resolved the problem of the wastelands the problem of no religion i think is simple
just copy paste from a working province to a no religion one. 
Just copied culture and religion from Kas Rhun to khundolan and it seems the issue was resolved tomorrow I will give it a better look

**Comment by Rigmored** [comment]
I think there is still a problem, which is the problem we had originally, the provinces have noreligion

**Comment by RiccoPT** [comment]
i will try to resolve it today

**Comment by RiccoPT** [comment]
No Religion bug fixed on all proivinces
